#!/bin/sh
# Check that modified files have got updated copyrights for the current year
# Copyright (c) 2026 IBM Corporation. All Rights Reserved.

rcFile="/tmp/pyCheckCopyright.$$"

cd ..
currentYear=`date "+%Y"`
echo 0 > $rcFile

# Which files are different from the public repo
git diff origin -- | grep "^+++" | sed "s!+++ b/!!g" |\
  while read f
do
  grep -qi "copyright" ./$f
  if [ $? -eq 0 ]
  then
    grep -qi "copyright.*$currentYear" ./$f
    if [ $? -ne 0 ]
    then
      echo "      " ./$f
      echo 1 > $rcFile
    else
      : echo NewCR ./$f
    fi
  fi
done
rc=`cat $rcFile`
rm -f $rcFile
exit $rc

