#!/bin/bash

# This script checks the MQCA_ constants where we might need to know the corresponding
# maximum attribute length so that MQINQ/MQSET verbs can be passed a correctly-sized buffer.
# New versions of MQ might introduce new attributes, and hence we might need to either update
# the mqinq.py or the exclusions file.
#
# The program is run during the copyDefs process and also from the main "check" release-gating process.
# Missing attributes cause this program to fail.

tmpfile=/tmp/checkCA.$$
src=$1
targ=$2
exclusion=$3

if [ -z "$src" ]
then
  # pick one of the definition files
  src=../code/ibmmq/_CMQC_linux_arm64.py
fi

if [ -z "$targ" ]
then
  targ=../code/ibmmq/mqinq.py
fi

if [ -z "$exclusion" ]
then
  exclusion=./checkCA.exclusion
fi

for f in $src $targ $exclusion
do
  if [ ! -r "$f" ]
  then
    echo "Cannot read $f"
    exit 1
  fi
done

# The exclusion list gives MQCA attributes that we know we don't need to include in the mqAttrLen block.
# Any new MQCA constants that show up will need to be added either into this exclusion list or
# the mqAttrLength in mqinq.py.

# First remove any comments from the exclusion list by sending it to a tmpfile.
grep "^MQCA_" $exclusion | awk '{print $1}' > $tmpfile.1

# For everything in the CMQC definitions, does it exist in the Python source file? If not, is
# it in the exclusion list? If not there, then it's an error.
> $tmpfile.2
grep MQCA_ $src | awk '{print $1}' | while read ca
do
  grep -q "^[ ]*CMQC.$ca:" $targ
  if [ $? -ne 0 ]
  then
    grep -q "^$ca$" $tmpfile.1
    if [ $? -ne 0 ]
    then
      echo "Missing CA attribute: " $ca >> $tmpfile.2
    else
      : echo "Found attribute $ca in exclusion list"
    fi
  else
    : echo "Found attribute $ca in source file"
  fi
done

# This file will either contain details of the missing attributes or be empty
if [  -s $tmpfile.2 ]
then
  cat $tmpfile.2
  rc=1
else
  echo "No missing CA variables"
  rc=0
fi

rm $tmpfile.1 $tmpfile.2
exit $rc
