#!/bin/bash

# Make sure we can compile against the oldest "supported" level of MQ (9.1)
# Assumes the MQ installation is under /opt/mqm.91

curdir=`pwd`

# Location of old header files
export MQ_FILE_PATH=/opt/mqm.91

venv=../../venv
. $venv/bin/activate
pip uninstall -y ibmmq
cd ..

# Do an install of the local tree to check it builds
pip install --verbose -e .
pip list 2>&1| grep -q ibmmq
if [ $? -ne 0 ]
then
  echo "ERROR: Could not install ibmmq"
  exit 1
fi

# MQ 9.1.5 Redist Client package does not have setmqenv, so
# we fake it and export the symbols that might be relevant
$MQ_FILE_PATH/bin/crtmqenv -k -s > /tmp/crtmqenv
. /tmp/crtmqenv
export LD_LIBRARY_PATH
export PATH
export MQ_INSTALLATION_NAME
export MQ_INSTALLATION_PATH

# Now try to connect as a client to the qmgr. Since my machine
# is using the redist client package, it can't rely on version-switching
# to use local bindings.
python $curdir/../code/examples/connect_client.py
exit $?

