#!/bin/bash

# Run some linting processes against the Python modules
# We'll use both flake8 and pylint which show different things.

curdir=`pwd`
root=$curdir/..

# My VENV directory where flake8 is installed
venv=venv_ibmmq
. $root/../$venv/bin/activate
if [ $? -ne 0 ]
then
  echo "ERROR: Cannot activate venv: $venv"
  exit 1
fi

# Uncomment these lines the first time we create the VENV
# pip install flake8 pylint
# pip install ddt

if false
then
pip uninstall -y ibmmq >/dev/null 2>&1
cd $root
pip install -e .
fi

dirs=""
dirs="$dirs $root/code/examples"
dirs="$dirs $root/code/ibmmq"
dirs="$dirs $root/code/tests"
files="setup.py"

args="$*"
if [ -z "$args" ]
then
  args="."
fi

for d in $dirs $files
do
  if [ -d $d ]
  then
    cd $d
  else
    cd $root
    args=$d
  fi

  # Lots of complaints that classes from the "typing" module
  # are not used. But they ARE needed in the comment/annotation processing.
  flake8 --config=$root/tox.ini $args | grep -v typing

  export PYTHONPATH=$root/code/ibmmq:.
  # Examples have a lot of variables that really should be considered constants so we
  # bypass that subclass of the invalid-name test via the pylintrc config. Some other explicit
  # warnings disabled in the source code with comment directives.
  pylint --rcfile=$root/pylintrc $args 2>&1 

done
