name: Release
on:
  # This lets us trigger using the "gh" command line
  workflow_dispatch:
    branches:
      - default

  # These blocks can be uncommented to increase the automation - building
  # on PRs and attempting to release when a suitable tag is created

  # push:
  #  branches:
  #    - default
    # To simplify the release process, the publishing is triggered on tag.
    # We should make sure to only push tags for new releases.
    # If we start using tags for non-release purposes,
    # this needs to be updated.
    #
    # We need to explicitly configure an expression that matches anything.
  #  tags: [ "**" ]
  # pull_request:


env:
  REDIST_ROOT: "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/"
  LINUX_FILE: "IBM-MQC-Redist-LinuxX64.tar.gz"
  WINDOWS_FILE: "IBM-MQC-Redist-Win64.zip"
  VRMF: "9.4.5.0"

defaults:
  run:
    # Use bash on Windows for consistency.
    shell: bash

jobs:
  build_wheels:
    name: Build ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-22.04, windows-2022]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          python -m pip install -r tools/requirements-dev.txt

      - name: Get IBM MQ C Linux Redistributables
        if: matrix.runs-on == 'ubuntu-22.04'
        run: |
          python tools/getRedistributables.py "$REDIST_ROOT/$VRMF-$LINUX_FILE" ibm-mq-c

      - name: Get IBM MQ C Windows Redistributables
        if: matrix.runs-on == 'windows-2022'
        run: |
          python tools/getRedistributables.py "$REDIST_ROOT/$VRMF-$WINDOWS_FILE" ibm-mq-c

      - name: Build wheels
        run: |
          export MQ_FILE_PATH=`pwd`/ibm-mq-c
          python -m build --wheel

      - name: Check files
        run: ls -al dist/

      - name: Audit ABI3 wheels
        run: |
          abi3audit -vsS dist/*.whl

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-wheels-${{ matrix.runs-on }}
          path: ./dist/*.whl


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install build
        run: |
          python -m pip install build

      - name: Build sdist
        run: python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: dist/*.tar.gz


  complete_artifacts:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-22.04
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
          path: dist

      - name: Check files
        run: ls -al dist/

      # Uncomments this block to add auto-upload to PyPI when a new tag is created
      #- name: Publish to PyPI - on tag
        # Skip upload to PyPI if we don't have a tag
      #  if: startsWith(github.ref, 'refs/tags/')
      #  uses: pypa/gh-action-pypi-publish@release/v1
